# 1. Imagen base
FROM postgres:13

# 2. Copiar TODOS los *.sql numerados
#    Al estar en rutas distintas, los concatenamos en un solo COPY
COPY database/DDL/0*.sql   /docker-entrypoint-initdb.d/
COPY database/DML/0*.sql   /docker-entrypoint-initdb.d/

# 3. Variables de entorno
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=password
ENV POSTGRES_DB=SIIAPEC

# 4. Puerto por defecto
EXPOSE 5432
