# docker/Dockerfile.db
# ─────────────────────
# Imagen base actualizada (alpine ↓30–60 MB)

FROM postgres:16-alpine
# Postgres 16 estará soportado hasta nov-2028

# Copia de todos los scripts de inicialización numerados
COPY database/DDL/0*.sql  /docker-entrypoint-initdb.d/
COPY database/DML/0*.sql  /docker-entrypoint-initdb.d/

# Variables de entorno
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=password
ENV POSTGRES_DB=SIIAPEC

EXPOSE 5432
