-- insert_program_step.sql
INSERT INTO program_step (sequence, program_id, step_id) VALUES
(1, (SELECT id FROM program WHERE name='Maestría en Ingeniería Industrial'), 1),
(2, (SELECT id FROM program WHERE name='Maestría en Ingeniería Industrial'), 2),
(3, (SELECT id FROM program WHERE name='Maestría en Ingeniería Industrial'), 6),
(4, (SELECT id FROM program WHERE name='Maestría en Ingeniería Industrial'), 8),
(1, (SELECT id FROM program WHERE name='Maestría en Ingeniería Industrial'), 9),
(2, (SELECT id FROM program WHERE name='Maestría en Ingeniería Industrial'), 10),
(1, (SELECT id FROM program WHERE name='Maestría en Ingeniería Industrial'), 11),
(2, (SELECT id FROM program WHERE name='Maestría en Ingeniería Industrial'), 12),
(3, (SELECT id FROM program WHERE name='Maestría en Ingeniería Industrial'), 13),
(4, (SELECT id FROM program WHERE name='Maestría en Ingeniería Industrial'), 14),

(1, (SELECT id FROM program WHERE name='Maestría en Administración de Negocios Internacionales'), 1),
(2, (SELECT id FROM program WHERE name='Maestría en Administración de Negocios Internacionales'), 3),
(3, (SELECT id FROM program WHERE name='Maestría en Administración de Negocios Internacionales'), 6),
(4, (SELECT id FROM program WHERE name='Maestría en Administración de Negocios Internacionales'), 8),
(1, (SELECT id FROM program WHERE name='Maestría en Administración de Negocios Internacionales'), 9),
(2, (SELECT id FROM program WHERE name='Maestría en Administración de Negocios Internacionales'), 10),
(1, (SELECT id FROM program WHERE name='Maestría en Administración de Negocios Internacionales'), 11),
(2, (SELECT id FROM program WHERE name='Maestría en Administración de Negocios Internacionales'), 12),
(3, (SELECT id FROM program WHERE name='Maestría en Administración de Negocios Internacionales'), 13),
(4, (SELECT id FROM program WHERE name='Maestría en Administración de Negocios Internacionales'), 14),

(1, (SELECT id FROM program WHERE name='Maestría en Ingeniería Administrativa'), 1),
(2, (SELECT id FROM program WHERE name='Maestría en Ingeniería Administrativa'), 4),
(3, (SELECT id FROM program WHERE name='Maestría en Ingeniería Administrativa'), 6),
(4, (SELECT id FROM program WHERE name='Maestría en Ingeniería Administrativa'), 8),
(1, (SELECT id FROM program WHERE name='Maestría en Ingeniería Administrativa'), 9),
(2, (SELECT id FROM program WHERE name='Maestría en Ingeniería Administrativa'), 10),
(1, (SELECT id FROM program WHERE name='Maestría en Ingeniería Administrativa'), 11),
(2, (SELECT id FROM program WHERE name='Maestría en Ingeniería Administrativa'), 12),
(3, (SELECT id FROM program WHERE name='Maestría en Ingeniería Administrativa'), 13),
(4, (SELECT id FROM program WHERE name='Maestría en Ingeniería Administrativa'), 14),

(1, (SELECT id FROM program WHERE name='Doctorado en Ciencias de la Ingeniería'), 1),
(2, (SELECT id FROM program WHERE name='Doctorado en Ciencias de la Ingeniería'), 5),
(3, (SELECT id FROM program WHERE name='Doctorado en Ciencias de la Ingeniería'), 7),
(4, (SELECT id FROM program WHERE name='Doctorado en Ciencias de la Ingeniería'), 8),
(1, (SELECT id FROM program WHERE name='Doctorado en Ciencias de la Ingeniería'), 9),
(2, (SELECT id FROM program WHERE name='Doctorado en Ciencias de la Ingeniería'), 10),
(1, (SELECT id FROM program WHERE name='Doctorado en Ciencias de la Ingeniería'), 11),
(2, (SELECT id FROM program WHERE name='Doctorado en Ciencias de la Ingeniería'), 12),
(3, (SELECT id FROM program WHERE name='Doctorado en Ciencias de la Ingeniería'), 13),
(4, (SELECT id FROM program WHERE name='Doctorado en Ciencias de la Ingeniería'), 14);
