"""add_granular_permissions

Revision ID: 135a97882bf7
Revises: 7o5s7t8u9v0w
Create Date: 2026-04-17 08:15:07.966218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '135a97882bf7'
down_revision = '7o5s7t8u9v0w'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codename', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('resource', sa.String(length=60), nullable=False),
    sa.Column('perm_type', sa.String(length=10), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codename')
    )
    op.create_table('role_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    op.create_table('role_permission_override',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_permission_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('performed_by', sa.Integer(), nullable=False),
    sa.Column('performed_at', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('previous_state', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['performed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('granted_by', sa.Integer(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'permission_id', 'program_id', name='uq_user_permission_active')
    )
    with op.batch_alter_table('document_deadline', schema=None) as batch_op:
        batch_op.drop_index('ix_document_deadline_program_period')

    with op.batch_alter_table('document_template', schema=None) as batch_op:
        batch_op.alter_column('document_type',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.drop_index('ix_document_template_document_type')
        batch_op.drop_index('ix_document_template_program_id')
        batch_op.drop_constraint('document_template_program_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('document_template_created_by_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['created_by'], ['id'])
        batch_op.create_foreign_key(None, 'program', ['program_id'], ['id'])

    with op.batch_alter_table('enrollment_deferral', schema=None) as batch_op:
        batch_op.drop_index('ix_enrollment_deferral_status')
        batch_op.drop_index('ix_enrollment_deferral_user_program_id')

    with op.batch_alter_table('semester_enrollment', schema=None) as batch_op:
        batch_op.drop_index('ix_semester_enrollment_academic_period_id')
        batch_op.drop_index('ix_semester_enrollment_user_program_id')
        batch_op.drop_constraint('uq_semester_enrollment_up_period', type_='unique')

    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_constraint('fk_submission_document_deadline', type_='foreignkey')
        batch_op.create_foreign_key(None, 'document_deadline', ['document_deadline_id'], ['id'])

    with op.batch_alter_table('task_logs', schema=None) as batch_op:
        batch_op.drop_constraint('task_logs_task_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_logs', schema=None) as batch_op:
        batch_op.create_unique_constraint('task_logs_task_id_key', ['task_id'])

    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_submission_document_deadline', 'document_deadline', ['document_deadline_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('semester_enrollment', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_semester_enrollment_up_period', ['user_program_id', 'academic_period_id'])
        batch_op.create_index('ix_semester_enrollment_user_program_id', ['user_program_id'], unique=False)
        batch_op.create_index('ix_semester_enrollment_academic_period_id', ['academic_period_id'], unique=False)

    with op.batch_alter_table('enrollment_deferral', schema=None) as batch_op:
        batch_op.create_index('ix_enrollment_deferral_user_program_id', ['user_program_id'], unique=False)
        batch_op.create_index('ix_enrollment_deferral_status', ['status'], unique=False)

    with op.batch_alter_table('document_template', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('document_template_created_by_fkey', 'user', ['created_by'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('document_template_program_id_fkey', 'program', ['program_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index('ix_document_template_program_id', ['program_id'], unique=False)
        batch_op.create_index('ix_document_template_document_type', ['document_type'], unique=False)
        batch_op.alter_column('file_path',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=512),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('document_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)

    with op.batch_alter_table('document_deadline', schema=None) as batch_op:
        batch_op.create_index('ix_document_deadline_program_period', ['program_id', 'academic_period_id'], unique=False)

    op.drop_table('user_permission')
    op.drop_table('role_permission_audit')
    op.drop_table('role_permission_override')
    op.drop_table('role_permission')
    op.drop_table('permission')
    # ### end Alembic commands ###
