"""add action_url to notification

Revision ID: 1edfae1ae666
Revises: 6d2f5g7h9i0j
Create Date: 2026-03-15 13:48:10.728287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1edfae1ae666'
down_revision = '6d2f5g7h9i0j'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_period', schema=None) as batch_op:
        batch_op.drop_index('ix_academic_period_is_active')
        batch_op.drop_constraint('academic_period_created_by_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['created_by'], ['id'])

    with op.batch_alter_table('acceptance_document', schema=None) as batch_op:
        batch_op.drop_index('ix_acceptance_document_document_type')
        batch_op.drop_index('ix_acceptance_document_status')
        batch_op.drop_index('ix_acceptance_document_user_program_id')
        batch_op.drop_constraint('acceptance_document_user_program_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('acceptance_document_reviewed_by_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('acceptance_document_uploaded_by_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['uploaded_by_id'], ['id'])
        batch_op.create_foreign_key(None, 'user_program', ['user_program_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['reviewed_by_id'], ['id'])

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action_url', sa.String(length=500), nullable=True))

    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.alter_column('show_curriculum',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('show_hero_cards',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('show_objectives',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('show_graduate_profile',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('show_research_lines',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('show_contact_section',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('show_contact_form',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))

    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_index('ix_submission_academic_period_id')
        batch_op.drop_constraint('fk_submission_academic_period', type_='foreignkey')
        batch_op.create_foreign_key(None, 'academic_period', ['academic_period_id'], ['id'])

    with op.batch_alter_table('user_program', schema=None) as batch_op:
        batch_op.drop_index('ix_user_program_admission_period_id')
        batch_op.drop_index('ix_user_program_admission_status')
        batch_op.drop_constraint('fk_user_program_admission_period', type_='foreignkey')
        batch_op.drop_constraint('fk_user_program_decision_by', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['decision_by'], ['id'])
        batch_op.create_foreign_key(None, 'academic_period', ['admission_period_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_program', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_user_program_decision_by', 'user', ['decision_by'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_user_program_admission_period', 'academic_period', ['admission_period_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index('ix_user_program_admission_status', ['admission_status'], unique=False)
        batch_op.create_index('ix_user_program_admission_period_id', ['admission_period_id'], unique=False)

    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_submission_academic_period', 'academic_period', ['academic_period_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index('ix_submission_academic_period_id', ['academic_period_id'], unique=False)

    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.alter_column('show_contact_form',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('show_contact_section',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('show_research_lines',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('show_graduate_profile',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('show_objectives',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('show_hero_cards',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('show_curriculum',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('action_url')

    with op.batch_alter_table('acceptance_document', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('acceptance_document_uploaded_by_id_fkey', 'user', ['uploaded_by_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('acceptance_document_reviewed_by_id_fkey', 'user', ['reviewed_by_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('acceptance_document_user_program_id_fkey', 'user_program', ['user_program_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('ix_acceptance_document_user_program_id', ['user_program_id'], unique=False)
        batch_op.create_index('ix_acceptance_document_status', ['status'], unique=False)
        batch_op.create_index('ix_acceptance_document_document_type', ['document_type'], unique=False)

    with op.batch_alter_table('academic_period', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('academic_period_created_by_fkey', 'user', ['created_by'], ['id'], ondelete='SET NULL')
        batch_op.create_index('ix_academic_period_is_active', ['is_active'], unique=False)

    # ### end Alembic commands ###
