"""add to must change password to user

Revision ID: 255943a764d5
Revises: 79ab5a679144
Create Date: 2025-10-31 15:08:35.576225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '255943a764d5'
down_revision = '79ab5a679144'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('must_change_password', sa.Boolean(), nullable=False, server_default=sa.sql.expression.true()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('must_change_password')

    # ### end Alembic commands ###
