"""Cambiar forma de pedir una exteension

Revision ID: 5f9b5b5c42c1
Revises: cd1797c7c510
Create Date: 2025-09-29 02:16:42.612508

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5f9b5b5c42c1'
down_revision = 'cd1797c7c510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extension_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('archive_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('program_step_id', sa.Integer(), nullable=False))
        batch_op.alter_column('reason',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('requested_until',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_constraint('extension_request_submission_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('extension_request_decided_by_fkey', type_='foreignkey')
        batch_op.drop_constraint('extension_request_requested_by_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['decided_by'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'archive', ['archive_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'program_step', ['program_step_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['requested_by'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('submission_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extension_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submission_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('extension_request_requested_by_fkey', 'user', ['requested_by'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key('extension_request_decided_by_fkey', 'user', ['decided_by'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
        batch_op.create_foreign_key('extension_request_submission_id_fkey', 'submission', ['submission_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.alter_column('requested_until',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('reason',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('program_step_id')
        batch_op.drop_column('archive_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
