"""add to crated at and updated at to models

Revision ID: 8dacb6562759
Revises: b1765c803358
Create Date: 2025-11-03 09:03:19.431405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dacb6562759'
down_revision = 'b1765c803358'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Usar CURRENT_TIMESTAMP para PostgreSQL como server_default temporal
    # Agregar columnas con server_default temporal para evitar errores en datos existentes
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))

    with op.batch_alter_table('appointment_change_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))

    with op.batch_alter_table('archive', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))

    with op.batch_alter_table('event_slot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))

    with op.batch_alter_table('event_window', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))

    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))

    with op.batch_alter_table('program_change_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))

    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))

    with op.batch_alter_table('user_program', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))

    # Opcional: Remover los server_default después de agregar las columnas
    # Esto permite que SQLAlchemy maneje los defaults normalmente
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.alter_column('updated_at', server_default=None)

    with op.batch_alter_table('appointment_change_request', schema=None) as batch_op:
        batch_op.alter_column('updated_at', server_default=None)

    with op.batch_alter_table('archive', schema=None) as batch_op:
        batch_op.alter_column('created_at', server_default=None)
        batch_op.alter_column('updated_at', server_default=None)

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('updated_at', server_default=None)

    with op.batch_alter_table('event_slot', schema=None) as batch_op:
        batch_op.alter_column('updated_at', server_default=None)

    with op.batch_alter_table('event_window', schema=None) as batch_op:
        batch_op.alter_column('updated_at', server_default=None)

    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.alter_column('created_at', server_default=None)
        batch_op.alter_column('updated_at', server_default=None)

    with op.batch_alter_table('program_change_request', schema=None) as batch_op:
        batch_op.alter_column('updated_at', server_default=None)

    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.alter_column('updated_at', server_default=None)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('updated_at', server_default=None)

    with op.batch_alter_table('user_program', schema=None) as batch_op:
        batch_op.alter_column('updated_at', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_program', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('program_change_request', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('event_window', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('event_slot', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('archive', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('appointment_change_request', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
