"""add_event_capacity_and_windows_management

Revision ID: a7bf4aa361ef
Revises: 5f9b5b5c42c1
Create Date: 2025-09-30 18:10:00.973558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7bf4aa361ef'
down_revision = '5f9b5b5c42c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.Column('attended_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacity_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('max_capacity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('requires_registration', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('allows_attendance_tracking', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))

    with op.batch_alter_table('event_window', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slots_generated', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('current_capacity', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_window', schema=None) as batch_op:
        batch_op.drop_column('current_capacity')
        batch_op.drop_column('slots_generated')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('allows_attendance_tracking')
        batch_op.drop_column('requires_registration')
        batch_op.drop_column('max_capacity')
        batch_op.drop_column('capacity_type')

    op.drop_table('event_attendance')
    # ### end Alembic commands ###
