"""add user history and control number to user

Revision ID: b1765c803358
Revises: 255943a764d5
Create Date: 2025-10-31 22:03:25.984141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1765c803358'
down_revision = '255943a764d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.sql.expression.true()))
        batch_op.add_column(sa.Column('control_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('control_number_assigned_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['control_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('control_number_assigned_at')
        batch_op.drop_column('control_number')
        batch_op.drop_column('is_active')

    op.drop_table('user_history')
    # ### end Alembic commands ###
