"""add_complete_profile_fields_to_user

Revision ID: cd1797c7c510
Revises: fd16be08249d
Create Date: 2025-09-25 20:51:48.621589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd1797c7c510'
down_revision = 'fd16be08249d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('mobile_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('curp', sa.String(length=18), nullable=True))
        batch_op.add_column(sa.Column('rfc', sa.String(length=13), nullable=True))
        batch_op.add_column(sa.Column('birth_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('birth_place', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('cedula_profesional', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('nss', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_relationship', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('profile_completed', sa.Boolean(), nullable=False, server_default=sa.sql.expression.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_completed')
        batch_op.drop_column('emergency_contact_relationship')
        batch_op.drop_column('emergency_contact_phone')
        batch_op.drop_column('emergency_contact_name')
        batch_op.drop_column('nss')
        batch_op.drop_column('cedula_profesional')
        batch_op.drop_column('birth_place')
        batch_op.drop_column('birth_date')
        batch_op.drop_column('rfc')
        batch_op.drop_column('curp')
        batch_op.drop_column('address')
        batch_op.drop_column('mobile_phone')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
