"""Agregracion del campo de extencion

Revision ID: fd16be08249d
Revises: 220e09fdfab8
Create Date: 2025-09-25 16:54:02.960672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd16be08249d'
down_revision = '220e09fdfab8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archive', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_extension_request', sa.Boolean(), nullable=False,server_default=sa.sql.expression.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archive', schema=None) as batch_op:
        batch_op.drop_column('allow_extension_request')

    # ### end Alembic commands ###
